<?xml version="1.0" encoding="UTF-8" ?>
<Package name="NAOCadet" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="." xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="websocket_server" src="lib/websocket_server.py" />
        <File name="db" src="db.sqlite" />
        <File name="README" src="htdocs/blockly/accessible/README.md" />
        <File name="app.component" src="htdocs/blockly/accessible/app.component.js" />
        <File name="audio.service" src="htdocs/blockly/accessible/audio.service.js" />
        <File name="block-connection.service" src="htdocs/blockly/accessible/block-connection.service.js" />
        <File name="block-options-modal.component" src="htdocs/blockly/accessible/block-options-modal.component.js" />
        <File name="block-options-modal.service" src="htdocs/blockly/accessible/block-options-modal.service.js" />
        <File name="commonModal" src="htdocs/blockly/accessible/commonModal.js" />
        <File name="field-segment.component" src="htdocs/blockly/accessible/field-segment.component.js" />
        <File name="keyboard-input.service" src="htdocs/blockly/accessible/keyboard-input.service.js" />
        <File name="README" src="htdocs/blockly/accessible/libs/README" />
        <File name="Rx.umd.min" src="htdocs/blockly/accessible/libs/Rx.umd.min.js" />
        <File name="angular2-all.umd.min" src="htdocs/blockly/accessible/libs/angular2-all.umd.min.js" />
        <File name="angular2-polyfills.min" src="htdocs/blockly/accessible/libs/angular2-polyfills.min.js" />
        <File name="es6-shim.min" src="htdocs/blockly/accessible/libs/es6-shim.min.js" />
        <File name="accessible" src="htdocs/blockly/accessible/media/accessible.css" />
        <File name="click" src="htdocs/blockly/accessible/media/click.mp3" />
        <File name="click" src="htdocs/blockly/accessible/media/click.ogg" />
        <File name="click" src="htdocs/blockly/accessible/media/click.wav" />
        <File name="delete" src="htdocs/blockly/accessible/media/delete.mp3" />
        <File name="delete" src="htdocs/blockly/accessible/media/delete.ogg" />
        <File name="delete" src="htdocs/blockly/accessible/media/delete.wav" />
        <File name="oops" src="htdocs/blockly/accessible/media/oops.mp3" />
        <File name="oops" src="htdocs/blockly/accessible/media/oops.ogg" />
        <File name="oops" src="htdocs/blockly/accessible/media/oops.wav" />
        <File name="messages" src="htdocs/blockly/accessible/messages.js" />
        <File name="notifications.service" src="htdocs/blockly/accessible/notifications.service.js" />
        <File name="sidebar.component" src="htdocs/blockly/accessible/sidebar.component.js" />
        <File name="toolbox-modal.component" src="htdocs/blockly/accessible/toolbox-modal.component.js" />
        <File name="toolbox-modal.service" src="htdocs/blockly/accessible/toolbox-modal.service.js" />
        <File name="translate.pipe" src="htdocs/blockly/accessible/translate.pipe.js" />
        <File name="tree.service" src="htdocs/blockly/accessible/tree.service.js" />
        <File name="utils.service" src="htdocs/blockly/accessible/utils.service.js" />
        <File name="variable-add-modal.component" src="htdocs/blockly/accessible/variable-add-modal.component.js" />
        <File name="variable-modal.service" src="htdocs/blockly/accessible/variable-modal.service.js" />
        <File name="variable-remove-modal.component" src="htdocs/blockly/accessible/variable-remove-modal.component.js" />
        <File name="variable-rename-modal.component" src="htdocs/blockly/accessible/variable-rename-modal.component.js" />
        <File name="workspace-block.component" src="htdocs/blockly/accessible/workspace-block.component.js" />
        <File name="workspace.component" src="htdocs/blockly/accessible/workspace.component.js" />
        <File name="README" src="htdocs/blockly/appengine/README.txt" />
        <File name="app" src="htdocs/blockly/appengine/app.yaml" />
        <File name="apple-touch-icon" src="htdocs/blockly/appengine/apple-touch-icon.png" />
        <File name="favicon" src="htdocs/blockly/appengine/favicon.ico" />
        <File name="index" src="htdocs/blockly/appengine/index.yaml" />
        <File name="index_redirect" src="htdocs/blockly/appengine/index_redirect.py" />
        <File name="redirect" src="htdocs/blockly/appengine/redirect.html" />
        <File name="robots" src="htdocs/blockly/appengine/robots.txt" />
        <File name="storage" src="htdocs/blockly/appengine/storage.js" />
        <File name="storage" src="htdocs/blockly/appengine/storage.py" />
        <File name="blockly_accessible_compressed" src="htdocs/blockly/blockly_accessible_compressed.js" />
        <File name="blockly_accessible_uncompressed" src="htdocs/blockly/blockly_accessible_uncompressed.js" />
        <File name="blockly_compressed" src="htdocs/blockly/blockly_compressed.js" />
        <File name="blockly_uncompressed" src="htdocs/blockly/blockly_uncompressed.js" />
        <File name="colour" src="htdocs/blockly/blocks/colour.js" />
        <File name="lists" src="htdocs/blockly/blocks/lists.js" />
        <File name="logic" src="htdocs/blockly/blocks/logic.js" />
        <File name="loops" src="htdocs/blockly/blocks/loops.js" />
        <File name="math" src="htdocs/blockly/blocks/math.js" />
        <File name="procedures" src="htdocs/blockly/blocks/procedures.js" />
        <File name="text" src="htdocs/blockly/blocks/text.js" />
        <File name="variables" src="htdocs/blockly/blocks/variables.js" />
        <File name="blocks_compressed" src="htdocs/blockly/blocks_compressed.js" />
        <File name="build" src="htdocs/blockly/build.py" />
        <File name="block" src="htdocs/blockly/core/block.js" />
        <File name="block_drag_surface" src="htdocs/blockly/core/block_drag_surface.js" />
        <File name="block_dragger" src="htdocs/blockly/core/block_dragger.js" />
        <File name="block_render_svg" src="htdocs/blockly/core/block_render_svg.js" />
        <File name="block_svg" src="htdocs/blockly/core/block_svg.js" />
        <File name="blockly" src="htdocs/blockly/core/blockly.js" />
        <File name="blocks" src="htdocs/blockly/core/blocks.js" />
        <File name="bubble" src="htdocs/blockly/core/bubble.js" />
        <File name="comment" src="htdocs/blockly/core/comment.js" />
        <File name="connection" src="htdocs/blockly/core/connection.js" />
        <File name="connection_db" src="htdocs/blockly/core/connection_db.js" />
        <File name="constants" src="htdocs/blockly/core/constants.js" />
        <File name="contextmenu" src="htdocs/blockly/core/contextmenu.js" />
        <File name="css" src="htdocs/blockly/core/css.js" />
        <File name="dragged_connection_manager" src="htdocs/blockly/core/dragged_connection_manager.js" />
        <File name="events" src="htdocs/blockly/core/events.js" />
        <File name="extensions" src="htdocs/blockly/core/extensions.js" />
        <File name="field" src="htdocs/blockly/core/field.js" />
        <File name="field_angle" src="htdocs/blockly/core/field_angle.js" />
        <File name="field_checkbox" src="htdocs/blockly/core/field_checkbox.js" />
        <File name="field_colour" src="htdocs/blockly/core/field_colour.js" />
        <File name="field_date" src="htdocs/blockly/core/field_date.js" />
        <File name="field_dropdown" src="htdocs/blockly/core/field_dropdown.js" />
        <File name="field_image" src="htdocs/blockly/core/field_image.js" />
        <File name="field_label" src="htdocs/blockly/core/field_label.js" />
        <File name="field_number" src="htdocs/blockly/core/field_number.js" />
        <File name="field_textinput" src="htdocs/blockly/core/field_textinput.js" />
        <File name="field_variable" src="htdocs/blockly/core/field_variable.js" />
        <File name="flyout_base" src="htdocs/blockly/core/flyout_base.js" />
        <File name="flyout_button" src="htdocs/blockly/core/flyout_button.js" />
        <File name="flyout_dragger" src="htdocs/blockly/core/flyout_dragger.js" />
        <File name="flyout_horizontal" src="htdocs/blockly/core/flyout_horizontal.js" />
        <File name="flyout_vertical" src="htdocs/blockly/core/flyout_vertical.js" />
        <File name="generator" src="htdocs/blockly/core/generator.js" />
        <File name="gesture" src="htdocs/blockly/core/gesture.js" />
        <File name="grid" src="htdocs/blockly/core/grid.js" />
        <File name="icon" src="htdocs/blockly/core/icon.js" />
        <File name="inject" src="htdocs/blockly/core/inject.js" />
        <File name="input" src="htdocs/blockly/core/input.js" />
        <File name="msg" src="htdocs/blockly/core/msg.js" />
        <File name="mutator" src="htdocs/blockly/core/mutator.js" />
        <File name="names" src="htdocs/blockly/core/names.js" />
        <File name="options" src="htdocs/blockly/core/options.js" />
        <File name="procedures" src="htdocs/blockly/core/procedures.js" />
        <File name="rendered_connection" src="htdocs/blockly/core/rendered_connection.js" />
        <File name="scrollbar" src="htdocs/blockly/core/scrollbar.js" />
        <File name="toolbox" src="htdocs/blockly/core/toolbox.js" />
        <File name="tooltip" src="htdocs/blockly/core/tooltip.js" />
        <File name="touch" src="htdocs/blockly/core/touch.js" />
        <File name="trashcan" src="htdocs/blockly/core/trashcan.js" />
        <File name="ui_menu_utils" src="htdocs/blockly/core/ui_menu_utils.js" />
        <File name="utils" src="htdocs/blockly/core/utils.js" />
        <File name="variable_map" src="htdocs/blockly/core/variable_map.js" />
        <File name="variable_model" src="htdocs/blockly/core/variable_model.js" />
        <File name="variables" src="htdocs/blockly/core/variables.js" />
        <File name="warning" src="htdocs/blockly/core/warning.js" />
        <File name="widgetdiv" src="htdocs/blockly/core/widgetdiv.js" />
        <File name="workspace" src="htdocs/blockly/core/workspace.js" />
        <File name="workspace_audio" src="htdocs/blockly/core/workspace_audio.js" />
        <File name="workspace_drag_surface_svg" src="htdocs/blockly/core/workspace_drag_surface_svg.js" />
        <File name="workspace_dragger" src="htdocs/blockly/core/workspace_dragger.js" />
        <File name="workspace_svg" src="htdocs/blockly/core/workspace_svg.js" />
        <File name="xml" src="htdocs/blockly/core/xml.js" />
        <File name="zoom_controls" src="htdocs/blockly/core/zoom_controls.js" />
        <File name="dart_compressed" src="htdocs/blockly/dart_compressed.js" />
        <File name="svg-externs" src="htdocs/blockly/externs/svg-externs.js" />
        <File name="dart" src="htdocs/blockly/generators/dart.js" />
        <File name="colour" src="htdocs/blockly/generators/dart/colour.js" />
        <File name="lists" src="htdocs/blockly/generators/dart/lists.js" />
        <File name="logic" src="htdocs/blockly/generators/dart/logic.js" />
        <File name="loops" src="htdocs/blockly/generators/dart/loops.js" />
        <File name="math" src="htdocs/blockly/generators/dart/math.js" />
        <File name="procedures" src="htdocs/blockly/generators/dart/procedures.js" />
        <File name="text" src="htdocs/blockly/generators/dart/text.js" />
        <File name="variables" src="htdocs/blockly/generators/dart/variables.js" />
        <File name="javascript" src="htdocs/blockly/generators/javascript.js" />
        <File name="colour" src="htdocs/blockly/generators/javascript/colour.js" />
        <File name="lists" src="htdocs/blockly/generators/javascript/lists.js" />
        <File name="logic" src="htdocs/blockly/generators/javascript/logic.js" />
        <File name="loops" src="htdocs/blockly/generators/javascript/loops.js" />
        <File name="math" src="htdocs/blockly/generators/javascript/math.js" />
        <File name="procedures" src="htdocs/blockly/generators/javascript/procedures.js" />
        <File name="text" src="htdocs/blockly/generators/javascript/text.js" />
        <File name="variables" src="htdocs/blockly/generators/javascript/variables.js" />
        <File name="lua" src="htdocs/blockly/generators/lua.js" />
        <File name="colour" src="htdocs/blockly/generators/lua/colour.js" />
        <File name="lists" src="htdocs/blockly/generators/lua/lists.js" />
        <File name="logic" src="htdocs/blockly/generators/lua/logic.js" />
        <File name="loops" src="htdocs/blockly/generators/lua/loops.js" />
        <File name="math" src="htdocs/blockly/generators/lua/math.js" />
        <File name="procedures" src="htdocs/blockly/generators/lua/procedures.js" />
        <File name="text" src="htdocs/blockly/generators/lua/text.js" />
        <File name="variables" src="htdocs/blockly/generators/lua/variables.js" />
        <File name="php" src="htdocs/blockly/generators/php.js" />
        <File name="colour" src="htdocs/blockly/generators/php/colour.js" />
        <File name="lists" src="htdocs/blockly/generators/php/lists.js" />
        <File name="logic" src="htdocs/blockly/generators/php/logic.js" />
        <File name="loops" src="htdocs/blockly/generators/php/loops.js" />
        <File name="math" src="htdocs/blockly/generators/php/math.js" />
        <File name="procedures" src="htdocs/blockly/generators/php/procedures.js" />
        <File name="text" src="htdocs/blockly/generators/php/text.js" />
        <File name="variables" src="htdocs/blockly/generators/php/variables.js" />
        <File name="python" src="htdocs/blockly/generators/python.js" />
        <File name="colour" src="htdocs/blockly/generators/python/colour.js" />
        <File name="lists" src="htdocs/blockly/generators/python/lists.js" />
        <File name="logic" src="htdocs/blockly/generators/python/logic.js" />
        <File name="loops" src="htdocs/blockly/generators/python/loops.js" />
        <File name="math" src="htdocs/blockly/generators/python/math.js" />
        <File name="procedures" src="htdocs/blockly/generators/python/procedures.js" />
        <File name="text" src="htdocs/blockly/generators/python/text.js" />
        <File name="variables" src="htdocs/blockly/generators/python/variables.js" />
        <File name="common" src="htdocs/blockly/i18n/common.py" />
        <File name="common" src="htdocs/blockly/i18n/common.pyc" />
        <File name="create_messages" src="htdocs/blockly/i18n/create_messages.py" />
        <File name="dedup_json" src="htdocs/blockly/i18n/dedup_json.py" />
        <File name="js_to_json" src="htdocs/blockly/i18n/js_to_json.py" />
        <File name="json_to_js" src="htdocs/blockly/i18n/json_to_js.py" />
        <File name="tests" src="htdocs/blockly/i18n/tests.py" />
        <File name="xliff_to_json" src="htdocs/blockly/i18n/xliff_to_json.py" />
        <File name="javascript_compressed" src="htdocs/blockly/javascript_compressed.js" />
        <File name="lua_compressed" src="htdocs/blockly/lua_compressed.js" />
        <File name="1x1" src="htdocs/blockly/media/1x1.gif" />
        <File name="click" src="htdocs/blockly/media/click.mp3" />
        <File name="click" src="htdocs/blockly/media/click.ogg" />
        <File name="click" src="htdocs/blockly/media/click.wav" />
        <File name="delete" src="htdocs/blockly/media/delete.mp3" />
        <File name="delete" src="htdocs/blockly/media/delete.ogg" />
        <File name="delete" src="htdocs/blockly/media/delete.wav" />
        <File name="disconnect" src="htdocs/blockly/media/disconnect.mp3" />
        <File name="disconnect" src="htdocs/blockly/media/disconnect.ogg" />
        <File name="disconnect" src="htdocs/blockly/media/disconnect.wav" />
        <File name="handclosed" src="htdocs/blockly/media/handclosed.cur" />
        <File name="handdelete" src="htdocs/blockly/media/handdelete.cur" />
        <File name="handopen" src="htdocs/blockly/media/handopen.cur" />
        <File name="quote0" src="htdocs/blockly/media/quote0.png" />
        <File name="quote1" src="htdocs/blockly/media/quote1.png" />
        <File name="sprites" src="htdocs/blockly/media/sprites.png" />
        <File name="sprites" src="htdocs/blockly/media/sprites.svg" />
        <File name="ab" src="htdocs/blockly/msg/js/ab.js" />
        <File name="ar" src="htdocs/blockly/msg/js/ar.js" />
        <File name="az" src="htdocs/blockly/msg/js/az.js" />
        <File name="ba" src="htdocs/blockly/msg/js/ba.js" />
        <File name="bcc" src="htdocs/blockly/msg/js/bcc.js" />
        <File name="be-tarask" src="htdocs/blockly/msg/js/be-tarask.js" />
        <File name="be" src="htdocs/blockly/msg/js/be.js" />
        <File name="bg" src="htdocs/blockly/msg/js/bg.js" />
        <File name="bn" src="htdocs/blockly/msg/js/bn.js" />
        <File name="br" src="htdocs/blockly/msg/js/br.js" />
        <File name="ca" src="htdocs/blockly/msg/js/ca.js" />
        <File name="cs" src="htdocs/blockly/msg/js/cs.js" />
        <File name="da" src="htdocs/blockly/msg/js/da.js" />
        <File name="de" src="htdocs/blockly/msg/js/de.js" />
        <File name="diq" src="htdocs/blockly/msg/js/diq.js" />
        <File name="el" src="htdocs/blockly/msg/js/el.js" />
        <File name="en-gb" src="htdocs/blockly/msg/js/en-gb.js" />
        <File name="en" src="htdocs/blockly/msg/js/en.js" />
        <File name="eo" src="htdocs/blockly/msg/js/eo.js" />
        <File name="es" src="htdocs/blockly/msg/js/es.js" />
        <File name="et" src="htdocs/blockly/msg/js/et.js" />
        <File name="eu" src="htdocs/blockly/msg/js/eu.js" />
        <File name="fa" src="htdocs/blockly/msg/js/fa.js" />
        <File name="fi" src="htdocs/blockly/msg/js/fi.js" />
        <File name="fr" src="htdocs/blockly/msg/js/fr.js" />
        <File name="he" src="htdocs/blockly/msg/js/he.js" />
        <File name="hi" src="htdocs/blockly/msg/js/hi.js" />
        <File name="hrx" src="htdocs/blockly/msg/js/hrx.js" />
        <File name="hu" src="htdocs/blockly/msg/js/hu.js" />
        <File name="ia" src="htdocs/blockly/msg/js/ia.js" />
        <File name="id" src="htdocs/blockly/msg/js/id.js" />
        <File name="is" src="htdocs/blockly/msg/js/is.js" />
        <File name="it" src="htdocs/blockly/msg/js/it.js" />
        <File name="ja" src="htdocs/blockly/msg/js/ja.js" />
        <File name="kab" src="htdocs/blockly/msg/js/kab.js" />
        <File name="ko" src="htdocs/blockly/msg/js/ko.js" />
        <File name="lb" src="htdocs/blockly/msg/js/lb.js" />
        <File name="lki" src="htdocs/blockly/msg/js/lki.js" />
        <File name="lrc" src="htdocs/blockly/msg/js/lrc.js" />
        <File name="lt" src="htdocs/blockly/msg/js/lt.js" />
        <File name="lv" src="htdocs/blockly/msg/js/lv.js" />
        <File name="mk" src="htdocs/blockly/msg/js/mk.js" />
        <File name="ms" src="htdocs/blockly/msg/js/ms.js" />
        <File name="nb" src="htdocs/blockly/msg/js/nb.js" />
        <File name="nl" src="htdocs/blockly/msg/js/nl.js" />
        <File name="oc" src="htdocs/blockly/msg/js/oc.js" />
        <File name="pl" src="htdocs/blockly/msg/js/pl.js" />
        <File name="pms" src="htdocs/blockly/msg/js/pms.js" />
        <File name="pt-br" src="htdocs/blockly/msg/js/pt-br.js" />
        <File name="pt" src="htdocs/blockly/msg/js/pt.js" />
        <File name="ro" src="htdocs/blockly/msg/js/ro.js" />
        <File name="ru" src="htdocs/blockly/msg/js/ru.js" />
        <File name="sc" src="htdocs/blockly/msg/js/sc.js" />
        <File name="sd" src="htdocs/blockly/msg/js/sd.js" />
        <File name="shn" src="htdocs/blockly/msg/js/shn.js" />
        <File name="sk" src="htdocs/blockly/msg/js/sk.js" />
        <File name="sl" src="htdocs/blockly/msg/js/sl.js" />
        <File name="sq" src="htdocs/blockly/msg/js/sq.js" />
        <File name="sr" src="htdocs/blockly/msg/js/sr.js" />
        <File name="sv" src="htdocs/blockly/msg/js/sv.js" />
        <File name="ta" src="htdocs/blockly/msg/js/ta.js" />
        <File name="tcy" src="htdocs/blockly/msg/js/tcy.js" />
        <File name="th" src="htdocs/blockly/msg/js/th.js" />
        <File name="tl" src="htdocs/blockly/msg/js/tl.js" />
        <File name="tlh" src="htdocs/blockly/msg/js/tlh.js" />
        <File name="tr" src="htdocs/blockly/msg/js/tr.js" />
        <File name="uk" src="htdocs/blockly/msg/js/uk.js" />
        <File name="vi" src="htdocs/blockly/msg/js/vi.js" />
        <File name="zh-hans" src="htdocs/blockly/msg/js/zh-hans.js" />
        <File name="zh-hant" src="htdocs/blockly/msg/js/zh-hant.js" />
        <File name="ab" src="htdocs/blockly/msg/json/ab.json" />
        <File name="ar" src="htdocs/blockly/msg/json/ar.json" />
        <File name="az" src="htdocs/blockly/msg/json/az.json" />
        <File name="ba" src="htdocs/blockly/msg/json/ba.json" />
        <File name="bcc" src="htdocs/blockly/msg/json/bcc.json" />
        <File name="be-tarask" src="htdocs/blockly/msg/json/be-tarask.json" />
        <File name="be" src="htdocs/blockly/msg/json/be.json" />
        <File name="bg" src="htdocs/blockly/msg/json/bg.json" />
        <File name="bn" src="htdocs/blockly/msg/json/bn.json" />
        <File name="br" src="htdocs/blockly/msg/json/br.json" />
        <File name="ca" src="htdocs/blockly/msg/json/ca.json" />
        <File name="constants" src="htdocs/blockly/msg/json/constants.json" />
        <File name="cs" src="htdocs/blockly/msg/json/cs.json" />
        <File name="da" src="htdocs/blockly/msg/json/da.json" />
        <File name="de" src="htdocs/blockly/msg/json/de.json" />
        <File name="diq" src="htdocs/blockly/msg/json/diq.json" />
        <File name="el" src="htdocs/blockly/msg/json/el.json" />
        <File name="en-gb" src="htdocs/blockly/msg/json/en-gb.json" />
        <File name="en" src="htdocs/blockly/msg/json/en.json" />
        <File name="eo" src="htdocs/blockly/msg/json/eo.json" />
        <File name="es" src="htdocs/blockly/msg/json/es.json" />
        <File name="et" src="htdocs/blockly/msg/json/et.json" />
        <File name="eu" src="htdocs/blockly/msg/json/eu.json" />
        <File name="fa" src="htdocs/blockly/msg/json/fa.json" />
        <File name="fi" src="htdocs/blockly/msg/json/fi.json" />
        <File name="fr" src="htdocs/blockly/msg/json/fr.json" />
        <File name="he" src="htdocs/blockly/msg/json/he.json" />
        <File name="hi" src="htdocs/blockly/msg/json/hi.json" />
        <File name="hrx" src="htdocs/blockly/msg/json/hrx.json" />
        <File name="hu" src="htdocs/blockly/msg/json/hu.json" />
        <File name="ia" src="htdocs/blockly/msg/json/ia.json" />
        <File name="id" src="htdocs/blockly/msg/json/id.json" />
        <File name="is" src="htdocs/blockly/msg/json/is.json" />
        <File name="it" src="htdocs/blockly/msg/json/it.json" />
        <File name="ja" src="htdocs/blockly/msg/json/ja.json" />
        <File name="kab" src="htdocs/blockly/msg/json/kab.json" />
        <File name="ko" src="htdocs/blockly/msg/json/ko.json" />
        <File name="lb" src="htdocs/blockly/msg/json/lb.json" />
        <File name="lki" src="htdocs/blockly/msg/json/lki.json" />
        <File name="lrc" src="htdocs/blockly/msg/json/lrc.json" />
        <File name="lt" src="htdocs/blockly/msg/json/lt.json" />
        <File name="lv" src="htdocs/blockly/msg/json/lv.json" />
        <File name="mk" src="htdocs/blockly/msg/json/mk.json" />
        <File name="ms" src="htdocs/blockly/msg/json/ms.json" />
        <File name="nb" src="htdocs/blockly/msg/json/nb.json" />
        <File name="nl" src="htdocs/blockly/msg/json/nl.json" />
        <File name="oc" src="htdocs/blockly/msg/json/oc.json" />
        <File name="pl" src="htdocs/blockly/msg/json/pl.json" />
        <File name="pms" src="htdocs/blockly/msg/json/pms.json" />
        <File name="pt-br" src="htdocs/blockly/msg/json/pt-br.json" />
        <File name="pt" src="htdocs/blockly/msg/json/pt.json" />
        <File name="qqq" src="htdocs/blockly/msg/json/qqq.json" />
        <File name="ro" src="htdocs/blockly/msg/json/ro.json" />
        <File name="ru" src="htdocs/blockly/msg/json/ru.json" />
        <File name="sc" src="htdocs/blockly/msg/json/sc.json" />
        <File name="sd" src="htdocs/blockly/msg/json/sd.json" />
        <File name="shn" src="htdocs/blockly/msg/json/shn.json" />
        <File name="sk" src="htdocs/blockly/msg/json/sk.json" />
        <File name="sl" src="htdocs/blockly/msg/json/sl.json" />
        <File name="sq" src="htdocs/blockly/msg/json/sq.json" />
        <File name="sr" src="htdocs/blockly/msg/json/sr.json" />
        <File name="sv" src="htdocs/blockly/msg/json/sv.json" />
        <File name="synonyms" src="htdocs/blockly/msg/json/synonyms.json" />
        <File name="ta" src="htdocs/blockly/msg/json/ta.json" />
        <File name="tcy" src="htdocs/blockly/msg/json/tcy.json" />
        <File name="th" src="htdocs/blockly/msg/json/th.json" />
        <File name="tl" src="htdocs/blockly/msg/json/tl.json" />
        <File name="tlh" src="htdocs/blockly/msg/json/tlh.json" />
        <File name="tr" src="htdocs/blockly/msg/json/tr.json" />
        <File name="uk" src="htdocs/blockly/msg/json/uk.json" />
        <File name="vi" src="htdocs/blockly/msg/json/vi.json" />
        <File name="zh-hans" src="htdocs/blockly/msg/json/zh-hans.json" />
        <File name="zh-hant" src="htdocs/blockly/msg/json/zh-hant.json" />
        <File name="messages" src="htdocs/blockly/msg/messages.js" />
        <File name="package" src="htdocs/blockly/package.json" />
        <File name="php_compressed" src="htdocs/blockly/php_compressed.js" />
        <File name="python_compressed" src="htdocs/blockly/python_compressed.js" />
        <File name="close" src="htdocs/close.html" />
        <File name="bootstrap-select" src="htdocs/css/bootstrap-select.css" />
        <File name="bootstrap-select.css" src="htdocs/css/bootstrap-select.css.map" />
        <File name="bootstrap-select.min" src="htdocs/css/bootstrap-select.min.css" />
        <File name="bootstrap.min" src="htdocs/css/bootstrap.min.css" />
        <File name="bootstrap.min.css" src="htdocs/css/bootstrap.min.css.map" />
        <File name="cadet" src="htdocs/css/cadet.css" />
        <File name="font-awesome.min" src="htdocs/css/font-awesome.min.css" />
        <File name="laces" src="htdocs/css/laces.css" />
        <File name="FontAwesome" src="htdocs/fonts/FontAwesome.otf" />
        <File name="fontawesome-webfont" src="htdocs/fonts/fontawesome-webfont.eot" />
        <File name="fontawesome-webfont" src="htdocs/fonts/fontawesome-webfont.svg" />
        <File name="fontawesome-webfont" src="htdocs/fonts/fontawesome-webfont.ttf" />
        <File name="fontawesome-webfont" src="htdocs/fonts/fontawesome-webfont.woff" />
        <File name="fontawesome-webfont" src="htdocs/fonts/fontawesome-webfont.woff2" />
        <File name="roboto" src="htdocs/fonts/roboto.woff2" />
        <File name="tinkerbell_sayblock" src="htdocs/img/tinkerbell_sayblock.png" />
        <File name="index" src="htdocs/index.html" />
        <File name="acorn" src="htdocs/js/acorn.js" />
        <File name="blocks" src="htdocs/js/blocks.js" />
        <File name="blocks_custom" src="htdocs/js/blocks_custom.js" />
        <File name="bootstrap-select.js" src="htdocs/js/bootstrap-select.js.map" />
        <File name="bootstrap-select.min" src="htdocs/js/bootstrap-select.min.js" />
        <File name="bootstrap.min" src="htdocs/js/bootstrap.min.js" />
        <File name="bootstrap.min.js" src="htdocs/js/bootstrap.min.js.map" />
        <File name="cadet" src="htdocs/js/cadet.js" />
        <File name="html5shiv.min" src="htdocs/js/html5shiv.min.js" />
        <File name="defaults-ar_AR" src="htdocs/js/i18n/defaults-ar_AR.js" />
        <File name="defaults-ar_AR.min" src="htdocs/js/i18n/defaults-ar_AR.min.js" />
        <File name="defaults-bg_BG" src="htdocs/js/i18n/defaults-bg_BG.js" />
        <File name="defaults-bg_BG.min" src="htdocs/js/i18n/defaults-bg_BG.min.js" />
        <File name="defaults-cro_CRO" src="htdocs/js/i18n/defaults-cro_CRO.js" />
        <File name="defaults-cro_CRO.min" src="htdocs/js/i18n/defaults-cro_CRO.min.js" />
        <File name="defaults-cs_CZ" src="htdocs/js/i18n/defaults-cs_CZ.js" />
        <File name="defaults-cs_CZ.min" src="htdocs/js/i18n/defaults-cs_CZ.min.js" />
        <File name="defaults-da_DK" src="htdocs/js/i18n/defaults-da_DK.js" />
        <File name="defaults-da_DK.min" src="htdocs/js/i18n/defaults-da_DK.min.js" />
        <File name="defaults-de_DE" src="htdocs/js/i18n/defaults-de_DE.js" />
        <File name="defaults-de_DE.min" src="htdocs/js/i18n/defaults-de_DE.min.js" />
        <File name="defaults-en_US" src="htdocs/js/i18n/defaults-en_US.js" />
        <File name="defaults-en_US.min" src="htdocs/js/i18n/defaults-en_US.min.js" />
        <File name="defaults-es_CL" src="htdocs/js/i18n/defaults-es_CL.js" />
        <File name="defaults-es_CL.min" src="htdocs/js/i18n/defaults-es_CL.min.js" />
        <File name="defaults-es_ES" src="htdocs/js/i18n/defaults-es_ES.js" />
        <File name="defaults-es_ES.min" src="htdocs/js/i18n/defaults-es_ES.min.js" />
        <File name="defaults-et_EE" src="htdocs/js/i18n/defaults-et_EE.js" />
        <File name="defaults-eu" src="htdocs/js/i18n/defaults-eu.js" />
        <File name="defaults-eu.min" src="htdocs/js/i18n/defaults-eu.min.js" />
        <File name="defaults-fa_IR" src="htdocs/js/i18n/defaults-fa_IR.js" />
        <File name="defaults-fa_IR.min" src="htdocs/js/i18n/defaults-fa_IR.min.js" />
        <File name="defaults-fi_FI" src="htdocs/js/i18n/defaults-fi_FI.js" />
        <File name="defaults-fi_FI.min" src="htdocs/js/i18n/defaults-fi_FI.min.js" />
        <File name="defaults-fr_FR" src="htdocs/js/i18n/defaults-fr_FR.js" />
        <File name="defaults-fr_FR.min" src="htdocs/js/i18n/defaults-fr_FR.min.js" />
        <File name="defaults-hu_HU" src="htdocs/js/i18n/defaults-hu_HU.js" />
        <File name="defaults-hu_HU.min" src="htdocs/js/i18n/defaults-hu_HU.min.js" />
        <File name="defaults-id_ID" src="htdocs/js/i18n/defaults-id_ID.js" />
        <File name="defaults-id_ID.min" src="htdocs/js/i18n/defaults-id_ID.min.js" />
        <File name="defaults-it_IT" src="htdocs/js/i18n/defaults-it_IT.js" />
        <File name="defaults-it_IT.min" src="htdocs/js/i18n/defaults-it_IT.min.js" />
        <File name="defaults-ko_KR" src="htdocs/js/i18n/defaults-ko_KR.js" />
        <File name="defaults-ko_KR.min" src="htdocs/js/i18n/defaults-ko_KR.min.js" />
        <File name="defaults-lt_LT" src="htdocs/js/i18n/defaults-lt_LT.js" />
        <File name="defaults-lt_LT.min" src="htdocs/js/i18n/defaults-lt_LT.min.js" />
        <File name="defaults-nb_NO" src="htdocs/js/i18n/defaults-nb_NO.js" />
        <File name="defaults-nb_NO.min" src="htdocs/js/i18n/defaults-nb_NO.min.js" />
        <File name="defaults-nl_NL" src="htdocs/js/i18n/defaults-nl_NL.js" />
        <File name="defaults-nl_NL.min" src="htdocs/js/i18n/defaults-nl_NL.min.js" />
        <File name="defaults-pl_PL" src="htdocs/js/i18n/defaults-pl_PL.js" />
        <File name="defaults-pl_PL.min" src="htdocs/js/i18n/defaults-pl_PL.min.js" />
        <File name="defaults-pt_BR" src="htdocs/js/i18n/defaults-pt_BR.js" />
        <File name="defaults-pt_BR.min" src="htdocs/js/i18n/defaults-pt_BR.min.js" />
        <File name="defaults-pt_PT" src="htdocs/js/i18n/defaults-pt_PT.js" />
        <File name="defaults-pt_PT.min" src="htdocs/js/i18n/defaults-pt_PT.min.js" />
        <File name="defaults-ro_RO" src="htdocs/js/i18n/defaults-ro_RO.js" />
        <File name="defaults-ro_RO.min" src="htdocs/js/i18n/defaults-ro_RO.min.js" />
        <File name="defaults-ru_RU" src="htdocs/js/i18n/defaults-ru_RU.js" />
        <File name="defaults-ru_RU.min" src="htdocs/js/i18n/defaults-ru_RU.min.js" />
        <File name="defaults-sk_SK" src="htdocs/js/i18n/defaults-sk_SK.js" />
        <File name="defaults-sk_SK.min" src="htdocs/js/i18n/defaults-sk_SK.min.js" />
        <File name="defaults-sl_SI" src="htdocs/js/i18n/defaults-sl_SI.js" />
        <File name="defaults-sl_SI.min" src="htdocs/js/i18n/defaults-sl_SI.min.js" />
        <File name="defaults-sv_SE" src="htdocs/js/i18n/defaults-sv_SE.js" />
        <File name="defaults-sv_SE.min" src="htdocs/js/i18n/defaults-sv_SE.min.js" />
        <File name="defaults-tr_TR" src="htdocs/js/i18n/defaults-tr_TR.js" />
        <File name="defaults-tr_TR.min" src="htdocs/js/i18n/defaults-tr_TR.min.js" />
        <File name="defaults-ua_UA" src="htdocs/js/i18n/defaults-ua_UA.js" />
        <File name="defaults-ua_UA.min" src="htdocs/js/i18n/defaults-ua_UA.min.js" />
        <File name="defaults-zh_CN" src="htdocs/js/i18n/defaults-zh_CN.js" />
        <File name="defaults-zh_CN.min" src="htdocs/js/i18n/defaults-zh_CN.min.js" />
        <File name="defaults-zh_TW" src="htdocs/js/i18n/defaults-zh_TW.js" />
        <File name="defaults-zh_TW.min" src="htdocs/js/i18n/defaults-zh_TW.min.js" />
        <File name="ie10-viewport-bug-workaround" src="htdocs/js/ie10-viewport-bug-workaround.js" />
        <File name="interpreter" src="htdocs/js/interpreter.js" />
        <File name="jquery.min copy" src="htdocs/js/jquery.min copy.js" />
        <File name="jquery.min" src="htdocs/js/jquery.min.js" />
        <File name="laces" src="htdocs/js/laces.js" />
        <File name="nao" src="htdocs/js/nao.js" />
        <File name="popper.min" src="htdocs/js/popper.min.js" />
        <File name="popper.min.js" src="htdocs/js/popper.min.js.map" />
        <File name="respond.min" src="htdocs/js/respond.min.js" />
        <File name="workspace" src="htdocs/js/workspace.js" />
        <File name="naohead" src="htdocs/img/naohead.png" />
        <File name="card" src="htdocs/img/card.png" />
        <File name="cardedit" src="htdocs/img/cardedit.png" />
        <File name="cardlocked" src="htdocs/img/cardlocked.png" />
        <File name="acornauthors" src="htdocs/licenses/acornauthors.txt" />
        <File name="apache2license" src="htdocs/licenses/apache2license.txt" />
        <File name="cc0" src="htdocs/licenses/cc0.txt" />
        <File name="mitlicense" src="htdocs/licenses/mitlicense.txt" />
        <File name="soundauthors" src="htdocs/licenses/soundauthors.txt" />
        <File name="hardware_headjoint_3.3" src="htdocs/img/hardware_headjoint_3.3.png" />
        <File name="hardware_larmjoint_3.3" src="htdocs/img/hardware_larmjoint_3.3.png" />
        <File name="hardware_llegjoint" src="htdocs/img/hardware_llegjoint.png" />
        <File name="hardware_pelvisjoint" src="htdocs/img/hardware_pelvisjoint.png" />
        <File name="hardware_rarmjoint_3.3" src="htdocs/img/hardware_rarmjoint_3.3.png" />
        <File name="hardware_rlegjoint" src="htdocs/img/hardware_rlegjoint.png" />
        <File name="gnugplv3" src="htdocs/licenses/gnugplv3.txt" />
        <File name="loading" src="htdocs/img/loading.svg" />
        <File name="favicon" src="htdocs/favicon.ico" />
        <File name="Door Opening" src="scriptdocs/Door Opening.wav" />
        <File name="Running" src="scriptdocs/Running.wav" />
        <File name="Woosh" src="scriptdocs/Woosh.wav" />
    </Resources>
    <Topics />
    <IgnoredPaths />
</Package>
